// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: goat/v1/goat.proto

package goatv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GoatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sentence      string                 `protobuf:"bytes,1,opt,name=sentence,proto3" json:"sentence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoatRequest) Reset() {
	*x = GoatRequest{}
	mi := &file_goat_v1_goat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoatRequest) ProtoMessage() {}

func (x *GoatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goat_v1_goat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoatRequest.ProtoReflect.Descriptor instead.
func (*GoatRequest) Descriptor() ([]byte, []int) {
	return file_goat_v1_goat_proto_rawDescGZIP(), []int{0}
}

func (x *GoatRequest) GetSentence() string {
	if x != nil {
		return x.Sentence
	}
	return ""
}

type GoatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sentence      string                 `protobuf:"bytes,1,opt,name=sentence,proto3" json:"sentence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoatResponse) Reset() {
	*x = GoatResponse{}
	mi := &file_goat_v1_goat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoatResponse) ProtoMessage() {}

func (x *GoatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goat_v1_goat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoatResponse.ProtoReflect.Descriptor instead.
func (*GoatResponse) Descriptor() ([]byte, []int) {
	return file_goat_v1_goat_proto_rawDescGZIP(), []int{1}
}

func (x *GoatResponse) GetSentence() string {
	if x != nil {
		return x.Sentence
	}
	return ""
}

var File_goat_v1_goat_proto protoreflect.FileDescriptor

var file_goat_v1_goat_proto_rawDesc = string([]byte{
	0x0a, 0x12, 0x67, 0x6f, 0x61, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x6f, 0x61, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x6f, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x22, 0x29, 0x0a,
	0x0b, 0x47, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x65, 0x6e, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x65, 0x6e, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x2a, 0x0a, 0x0c, 0x47, 0x6f, 0x61, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x74,
	0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x74,
	0x65, 0x6e, 0x63, 0x65, 0x32, 0x44, 0x0a, 0x0b, 0x47, 0x6f, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x04, 0x47, 0x6f, 0x61, 0x74, 0x12, 0x14, 0x2e, 0x67, 0x6f,
	0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x67, 0x6f, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x6f, 0x61, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x70, 0x0a, 0x0b, 0x63, 0x6f,
	0x6d, 0x2e, 0x67, 0x6f, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x42, 0x09, 0x47, 0x6f, 0x61, 0x74, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x19, 0x67, 0x6f, 0x61, 0x74, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x61, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x67, 0x6f, 0x61, 0x74, 0x76,
	0x31, 0xa2, 0x02, 0x03, 0x47, 0x58, 0x58, 0xaa, 0x02, 0x07, 0x47, 0x6f, 0x61, 0x74, 0x2e, 0x56,
	0x31, 0xca, 0x02, 0x07, 0x47, 0x6f, 0x61, 0x74, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x13, 0x47, 0x6f,
	0x61, 0x74, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0xea, 0x02, 0x08, 0x47, 0x6f, 0x61, 0x74, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_goat_v1_goat_proto_rawDescOnce sync.Once
	file_goat_v1_goat_proto_rawDescData []byte
)

func file_goat_v1_goat_proto_rawDescGZIP() []byte {
	file_goat_v1_goat_proto_rawDescOnce.Do(func() {
		file_goat_v1_goat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goat_v1_goat_proto_rawDesc), len(file_goat_v1_goat_proto_rawDesc)))
	})
	return file_goat_v1_goat_proto_rawDescData
}

var file_goat_v1_goat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_goat_v1_goat_proto_goTypes = []any{
	(*GoatRequest)(nil),  // 0: goat.v1.GoatRequest
	(*GoatResponse)(nil), // 1: goat.v1.GoatResponse
}
var file_goat_v1_goat_proto_depIdxs = []int32{
	0, // 0: goat.v1.GoatService.Goat:input_type -> goat.v1.GoatRequest
	1, // 1: goat.v1.GoatService.Goat:output_type -> goat.v1.GoatResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_goat_v1_goat_proto_init() }
func file_goat_v1_goat_proto_init() {
	if File_goat_v1_goat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goat_v1_goat_proto_rawDesc), len(file_goat_v1_goat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_goat_v1_goat_proto_goTypes,
		DependencyIndexes: file_goat_v1_goat_proto_depIdxs,
		MessageInfos:      file_goat_v1_goat_proto_msgTypes,
	}.Build()
	File_goat_v1_goat_proto = out.File
	file_goat_v1_goat_proto_goTypes = nil
	file_goat_v1_goat_proto_depIdxs = nil
}
